### ISSUE TITLE
Add wrapper for wasm-gc

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#24]
While wasm-gc was discontinued, due to Rust having LTO turned on, it is still useful for other languages besides Rust.

https://github.com/alexcrichton/wasm-gc

**Comment by axic** [comment]
wasm-gc was replaced by https://github.com/rustwasm/wasm-snip

**Comment by fitzgen** [comment]
> wasm-gc was replaced by https://github.com/rustwasm/wasm-snip

Not quite true -- it is a pass that is built into the `walrus` crate now: https://docs.rs/walrus/0.8.0/walrus/passes/gc/index.html

It is true that `wasm-snip` runs that GC pass, though: https://github.com/rustwasm/wasm-snip/blob/master/src/lib.rs#L184

But what `wasm-snip` is really doing is taking things that *would otherwise never be GC'd and forcing them to be removed from the Wasm file*.

**Comment by axic** [comment]
@fitzgen thanks for the clarification! My comment was more aimed out our issue, that for the intent and purpose of our use case, snip indeed replaced gc :)
